import type { SymbolKind } from "@/context/OutlineContext";

export const SYMBOL_ICONS: Record<SymbolKind, string> = {
  file: "F",
  module: "M",
  namespace: "N",
  package: "P",
  class: "C",
  method: "m",
  property: "p",
  field: "f",
  constructor: "c",
  enum: "E",
  interface: "I",
  function: "f",
  variable: "v",
  constant: "K",
  string: "S",
  number: "#",
  boolean: "B",
  array: "[]",
  object: "{}",
  key: "k",
  null: "N",
  enumMember: "e",
  struct: "S",
  event: "e",
  operator: "o",
  typeParameter: "T",
};

export const SYMBOL_COLORS: Record<SymbolKind, string> = {
  file: "var(--cortex-text-primary)",
  module: "var(--cortex-text-primary)",
  namespace: "var(--cortex-syntax-function)",
  package: "var(--cortex-syntax-function)",
  class: "var(--cortex-syntax-function)",
  method: "var(--cortex-syntax-function)",
  property: "var(--cortex-syntax-variable)",
  field: "var(--cortex-syntax-variable)",
  constructor: "var(--cortex-syntax-function)",
  enum: "var(--cortex-syntax-function)",
  interface: "var(--cortex-syntax-function)",
  function: "var(--cortex-syntax-function)",
  variable: "var(--cortex-syntax-variable)",
  constant: "var(--cortex-info)",
  string: "var(--cortex-syntax-string)",
  number: "var(--cortex-syntax-number)",
  boolean: "var(--cortex-syntax-keyword)",
  array: "var(--cortex-text-primary)",
  object: "var(--cortex-text-primary)",
  key: "var(--cortex-syntax-variable)",
  null: "var(--cortex-syntax-keyword)",
  enumMember: "var(--cortex-info)",
  struct: "var(--cortex-syntax-function)",
  event: "var(--cortex-syntax-function)",
  operator: "var(--cortex-text-primary)",
  typeParameter: "var(--cortex-syntax-function)",
};
