import type { IconTheme } from "./types";

export const materialTheme: IconTheme = {
  id: "material",
  name: "Material",
  description: "Material Design inspired icons with vibrant colors",
  icons: {
    file: { icon: "📄", color: "#90a4ae" },
    folder: { icon: "📁", color: "#90a4ae" },
    folderOpen: { icon: "📂", color: "#90a4ae" },
    fileExtensions: {
      ts: { icon: "🔷", color: "#1976d2" },
      tsx: { icon: "⚛️", color: "#1976d2" },
      js: { icon: "🟨", color: "#ffca28" },
      jsx: { icon: "⚛️", color: "#ffca28" },
      mjs: { icon: "🟨", color: "#ffca28" },
      cjs: { icon: "🟨", color: "#ffca28" },
      html: { icon: "🌐", color: "#e44d26" },
      htm: { icon: "🌐", color: "#e44d26" },
      css: { icon: "🎨", color: "#42a5f5" },
      scss: { icon: "🎨", color: "#ec407a" },
      sass: { icon: "🎨", color: "#ec407a" },
      less: { icon: "🎨", color: "#1d365d" },
      vue: { icon: "💚", color: "#41b883" },
      svelte: { icon: "🔥", color: "#ff3e00" },
      json: { icon: "📋", color: "#fbc02d" },
      yaml: { icon: "⚙️", color: "#f44336" },
      yml: { icon: "⚙️", color: "#f44336" },
      toml: { icon: "⚙️", color: "#9c4121" },
      xml: { icon: "📄", color: "#ff6f00" },
      py: { icon: "🐍", color: "#4caf50" },
      rs: { icon: "🦀", color: "#ff7043" },
      go: { icon: "🐹", color: "#29b6f6" },
      java: { icon: "☕", color: "#f44336" },
      kt: { icon: "🟪", color: "#7c4dff" },
      swift: { icon: "🍎", color: "#ff5722" },
      c: { icon: "🔵", color: "#5c6bc0" },
      cpp: { icon: "🔵", color: "#5c6bc0" },
      cs: { icon: "🟢", color: "#66bb6a" },
      rb: { icon: "💎", color: "#e53935" },
      php: { icon: "🐘", color: "#7986cb" },
      sh: { icon: "💻", color: "#66bb6a" },
      bash: { icon: "💻", color: "#66bb6a" },
      md: { icon: "📝", color: "#42a5f5" },
      txt: { icon: "📄", color: "#90a4ae" },
      pdf: { icon: "📕", color: "#e53935" },
      svg: { icon: "🖼️", color: "#ffb300" },
      png: { icon: "🖼️", color: "#ab47bc" },
      jpg: { icon: "🖼️", color: "#ab47bc" },
      jpeg: { icon: "🖼️", color: "#ab47bc" },
      gif: { icon: "🖼️", color: "#ab47bc" },
      mp3: { icon: "🎵", color: "#e91e63" },
      mp4: { icon: "🎬", color: "#e53935" },
      zip: { icon: "📦", color: "#78909c" },
      sql: { icon: "🗃️", color: "#ffa000" },
      graphql: { icon: "💠", color: "#e535ab" },
      gql: { icon: "💠", color: "#e535ab" },
      lock: { icon: "🔒", color: "#78909c" },
      env: { icon: "🔐", color: "#ffc107" },
      log: { icon: "📜", color: "#78909c" },
    },
    fileNames: {
      "package.json": { icon: "📦", color: "#e53935" },
      "package-lock.json": { icon: "🔒", color: "#78909c" },
      "yarn.lock": { icon: "🔒", color: "#2196f3" },
      "tsconfig.json": { icon: "🔷", color: "#1976d2" },
      "jsconfig.json": { icon: "🟨", color: "#ffca28" },
      ".eslintrc": { icon: "📏", color: "#7c4dff" },
      ".eslintrc.js": { icon: "📏", color: "#7c4dff" },
      ".eslintrc.json": { icon: "📏", color: "#7c4dff" },
      ".prettierrc": { icon: "🎀", color: "#26a69a" },
      ".prettierrc.json": { icon: "🎀", color: "#26a69a" },
      "tailwind.config.js": { icon: "🌊", color: "#26c6da" },
      "tailwind.config.ts": { icon: "🌊", color: "#26c6da" },
      "vite.config.js": { icon: "⚡", color: "#7c4dff" },
      "vite.config.ts": { icon: "⚡", color: "#7c4dff" },
      "webpack.config.js": { icon: "📦", color: "#42a5f5" },
      ".gitignore": { icon: "🚫", color: "#ff5722" },
      "Dockerfile": { icon: "🐳", color: "#29b6f6" },
      "docker-compose.yml": { icon: "🐳", color: "#29b6f6" },
      "README.md": { icon: "📖", color: "#42a5f5" },
      "LICENSE": { icon: "⚖️", color: "#90a4ae" },
      "Makefile": { icon: "🔨", color: "#78909c" },
      "Cargo.toml": { icon: "🦀", color: "#ff7043" },
      "go.mod": { icon: "🐹", color: "#29b6f6" },
      ".env": { icon: "🔐", color: "#ffc107" },
      ".env.local": { icon: "🔐", color: "#ffc107" },
      "jest.config.js": { icon: "🃏", color: "#e53935" },
      "vitest.config.ts": { icon: "⚡", color: "#66bb6a" },
    },
    folderNames: {
      src: { icon: "📁", color: "#ffc107" },
      source: { icon: "📁", color: "#ffc107" },
      dist: { icon: "📁", color: "#78909c" },
      build: { icon: "📁", color: "#78909c" },
      node_modules: { icon: "📁", color: "#66bb6a" },
      components: { icon: "📁", color: "#42a5f5" },
      hooks: { icon: "📁", color: "#7c4dff" },
      utils: { icon: "📁", color: "#ffa000" },
      services: { icon: "📁", color: "#26c6da" },
      api: { icon: "📁", color: "#26c6da" },
      pages: { icon: "📁", color: "#66bb6a" },
      styles: { icon: "📁", color: "#ec407a" },
      assets: { icon: "📁", color: "#ff9800" },
      public: { icon: "📁", color: "#29b6f6" },
      config: { icon: "📁", color: "#78909c" },
      test: { icon: "📁", color: "#e53935" },
      tests: { icon: "📁", color: "#e53935" },
      docs: { icon: "📁", color: "#42a5f5" },
      types: { icon: "📁", color: "#1976d2" },
      models: { icon: "📁", color: "#9c27b0" },
      store: { icon: "📁", color: "#7c4dff" },
      context: { icon: "📁", color: "#7c4dff" },
      database: { icon: "📁", color: "#ffa000" },
      ".git": { icon: "📁", color: "#ff5722" },
      ".github": { icon: "📁", color: "#90a4ae" },
      ".vscode": { icon: "📁", color: "#29b6f6" },
      docker: { icon: "📁", color: "#29b6f6" },
    },
    folderNamesOpen: {},
  },
};

export const minimalTheme: IconTheme = {
  id: "minimal",
  name: "Minimal",
  description: "Clean, minimalist icons using simple shapes",
  icons: {
    file: { icon: "◻️", color: "#9ca3af" },
    folder: { icon: "▷", color: "#6b7280" },
    folderOpen: { icon: "▽", color: "#6b7280" },
    fileExtensions: {
      ts: { icon: "◆", color: "#3178c6" },
      tsx: { icon: "◆", color: "#3178c6" },
      js: { icon: "◆", color: "#f7df1e" },
      jsx: { icon: "◆", color: "#f7df1e" },
      mjs: { icon: "◆", color: "#f7df1e" },
      cjs: { icon: "◆", color: "#f7df1e" },
      html: { icon: "◆", color: "#e34c26" },
      css: { icon: "◆", color: "#563d7c" },
      scss: { icon: "◆", color: "#c6538c" },
      json: { icon: "◆", color: "#cbcb41" },
      yaml: { icon: "◆", color: "#cb171e" },
      yml: { icon: "◆", color: "#cb171e" },
      toml: { icon: "◆", color: "#9c4121" },
      py: { icon: "◆", color: "#3572a5" },
      rs: { icon: "◆", color: "#dea584" },
      go: { icon: "◆", color: "#00add8" },
      java: { icon: "◆", color: "#b07219" },
      kt: { icon: "◆", color: "#a97bff" },
      swift: { icon: "◆", color: "#f05138" },
      c: { icon: "◆", color: "#555555" },
      cpp: { icon: "◆", color: "#f34b7d" },
      cs: { icon: "◆", color: "#178600" },
      rb: { icon: "◆", color: "#701516" },
      php: { icon: "◆", color: "#4f5d95" },
      sh: { icon: "◆", color: "#89e051" },
      bash: { icon: "◆", color: "#89e051" },
      md: { icon: "◇", color: "#083fa1" },
      txt: { icon: "◻️", color: "#9ca3af" },
      pdf: { icon: "◇", color: "#ff0000" },
      svg: { icon: "◇", color: "#ffb13b" },
      png: { icon: "◇", color: "#a074c4" },
      jpg: { icon: "◇", color: "#a074c4" },
      jpeg: { icon: "◇", color: "#a074c4" },
      gif: { icon: "◇", color: "#a074c4" },
      mp3: { icon: "◇", color: "#e91e63" },
      mp4: { icon: "◇", color: "#f44336" },
      zip: { icon: "◇", color: "#6d8086" },
      sql: { icon: "◆", color: "#e38c00" },
      graphql: { icon: "◆", color: "#e535ab" },
      lock: { icon: "◈", color: "#525252" },
      env: { icon: "◈", color: "#faf743" },
      log: { icon: "◻️", color: "#6d8086" },
    },
    fileNames: {
      "package.json": { icon: "◈", color: "#e8274b" },
      "package-lock.json": { icon: "◈", color: "#525252" },
      "yarn.lock": { icon: "◈", color: "#2c8ebb" },
      "tsconfig.json": { icon: "◈", color: "#3178c6" },
      "jsconfig.json": { icon: "◈", color: "#f7df1e" },
      ".eslintrc": { icon: "◈", color: "#4b32c3" },
      ".eslintrc.js": { icon: "◈", color: "#4b32c3" },
      ".eslintrc.json": { icon: "◈", color: "#4b32c3" },
      ".prettierrc": { icon: "◈", color: "#56b3b4" },
      ".prettierrc.json": { icon: "◈", color: "#56b3b4" },
      "tailwind.config.js": { icon: "◈", color: "#38bdf8" },
      "tailwind.config.ts": { icon: "◈", color: "#38bdf8" },
      "vite.config.js": { icon: "◈", color: "#646cff" },
      "vite.config.ts": { icon: "◈", color: "#646cff" },
      ".gitignore": { icon: "◈", color: "#f05032" },
      "Dockerfile": { icon: "◈", color: "#2496ed" },
      "docker-compose.yml": { icon: "◈", color: "#2496ed" },
      "README.md": { icon: "◇", color: "#083fa1" },
      "LICENSE": { icon: "◇", color: "#9ca3af" },
      "Makefile": { icon: "◈", color: "#6d8086" },
      "Cargo.toml": { icon: "◈", color: "#dea584" },
      "go.mod": { icon: "◈", color: "#00add8" },
      ".env": { icon: "◈", color: "#faf743" },
      ".env.local": { icon: "◈", color: "#faf743" },
    },
    folderNames: {
      src: { icon: "▷", color: "#e8ba36" },
      dist: { icon: "▷", color: "#6d8086" },
      build: { icon: "▷", color: "#6d8086" },
      node_modules: { icon: "▷", color: "#8bc34a" },
      components: { icon: "▷", color: "#42a5f5" },
      hooks: { icon: "▷", color: "#7c4dff" },
      utils: { icon: "▷", color: "#ffb300" },
      services: { icon: "▷", color: "#00bcd4" },
      api: { icon: "▷", color: "#00bcd4" },
      pages: { icon: "▷", color: "#4caf50" },
      styles: { icon: "▷", color: "#e91e63" },
      assets: { icon: "▷", color: "#ff9800" },
      public: { icon: "▷", color: "#4fc3f7" },
      config: { icon: "▷", color: "#78909c" },
      test: { icon: "▷", color: "#c21325" },
      tests: { icon: "▷", color: "#c21325" },
      docs: { icon: "▷", color: "#42a5f5" },
      types: { icon: "▷", color: "#3178c6" },
      context: { icon: "▷", color: "#764abc" },
      ".git": { icon: "▷", color: "#f05032" },
      ".github": { icon: "▷", color: "#9ca3af" },
      ".vscode": { icon: "▷", color: "#007acc" },
    },
    folderNamesOpen: {
      src: { icon: "▽", color: "#e8ba36" },
      dist: { icon: "▽", color: "#6d8086" },
      build: { icon: "▽", color: "#6d8086" },
      node_modules: { icon: "▽", color: "#8bc34a" },
      components: { icon: "▽", color: "#42a5f5" },
      hooks: { icon: "▽", color: "#7c4dff" },
      utils: { icon: "▽", color: "#ffb300" },
      services: { icon: "▽", color: "#00bcd4" },
      api: { icon: "▽", color: "#00bcd4" },
      pages: { icon: "▽", color: "#4caf50" },
      styles: { icon: "▽", color: "#e91e63" },
      assets: { icon: "▽", color: "#ff9800" },
      public: { icon: "▽", color: "#4fc3f7" },
      config: { icon: "▽", color: "#78909c" },
      test: { icon: "▽", color: "#c21325" },
      tests: { icon: "▽", color: "#c21325" },
      docs: { icon: "▽", color: "#42a5f5" },
      types: { icon: "▽", color: "#3178c6" },
      context: { icon: "▽", color: "#764abc" },
      ".git": { icon: "▽", color: "#f05032" },
      ".github": { icon: "▽", color: "#9ca3af" },
      ".vscode": { icon: "▽", color: "#007acc" },
    },
  },
};
