import type { IconTheme } from "./types";
import { SETI_FILE_NAMES, SETI_FOLDER_NAMES } from "./themes-seti-data";

export const setiTheme: IconTheme = {
  id: "seti",
  name: "Seti",
  description: "Classic file icons inspired by Seti UI",
  icons: {
    file: { icon: "📄", color: "#d4d4d8" },
    folder: { icon: "📁", color: "#dcb67a" },
    folderOpen: { icon: "📂", color: "#dcb67a" },
    fileExtensions: {
      ts: { icon: "📘", color: "#3178c6" },
      tsx: { icon: "⚛️", color: "#3178c6" },
      js: { icon: "📒", color: "#f7df1e" },
      jsx: { icon: "⚛️", color: "#f7df1e" },
      mjs: { icon: "📒", color: "#f7df1e" },
      cjs: { icon: "📒", color: "#f7df1e" },
      html: { icon: "🌐", color: "#e34c26" },
      htm: { icon: "🌐", color: "#e34c26" },
      css: { icon: "🎨", color: "#563d7c" },
      scss: { icon: "🎨", color: "#c6538c" },
      sass: { icon: "🎨", color: "#c6538c" },
      less: { icon: "🎨", color: "#1d365d" },
      styl: { icon: "🎨", color: "#ff6347" },
      vue: { icon: "💚", color: "#42b883" },
      svelte: { icon: "🔥", color: "#ff3e00" },
      json: { icon: "📋", color: "#cbcb41" },
      jsonc: { icon: "📋", color: "#cbcb41" },
      json5: { icon: "📋", color: "#cbcb41" },
      yaml: { icon: "⚙️", color: "#cb171e" },
      yml: { icon: "⚙️", color: "#cb171e" },
      toml: { icon: "⚙️", color: "#9c4121" },
      xml: { icon: "📄", color: "#e37933" },
      ini: { icon: "⚙️", color: "#6d8086" },
      env: { icon: "🔐", color: "#faf743" },
      py: { icon: "🐍", color: "#3572a5" },
      pyw: { icon: "🐍", color: "#3572a5" },
      pyi: { icon: "🐍", color: "#3572a5" },
      rs: { icon: "🦀", color: "#dea584" },
      go: { icon: "🐹", color: "#00add8" },
      java: { icon: "☕", color: "#b07219" },
      kt: { icon: "🟣", color: "#a97bff" },
      kts: { icon: "🟣", color: "#a97bff" },
      swift: { icon: "🍎", color: "#f05138" },
      c: { icon: "🔷", color: "#555555" },
      cpp: { icon: "🔷", color: "#f34b7d" },
      cc: { icon: "🔷", color: "#f34b7d" },
      cxx: { icon: "🔷", color: "#f34b7d" },
      h: { icon: "📎", color: "#555555" },
      hpp: { icon: "📎", color: "#f34b7d" },
      hxx: { icon: "📎", color: "#f34b7d" },
      cs: { icon: "🟢", color: "#178600" },
      rb: { icon: "💎", color: "#701516" },
      php: { icon: "🐘", color: "#4f5d95" },
      lua: { icon: "🌙", color: "#000080" },
      r: { icon: "📊", color: "#198ce7" },
      scala: { icon: "🔴", color: "#c22d40" },
      clj: { icon: "🟢", color: "#db5855" },
      cljs: { icon: "🟢", color: "#db5855" },
      ex: { icon: "💧", color: "#6e4a7e" },
      exs: { icon: "💧", color: "#6e4a7e" },
      erl: { icon: "🔴", color: "#b83998" },
      hs: { icon: "🟣", color: "#5e5086" },
      ml: { icon: "🐫", color: "#dc6b19" },
      fs: { icon: "🔵", color: "#b845fc" },
      fsx: { icon: "🔵", color: "#b845fc" },
      nim: { icon: "👑", color: "#ffc200" },
      zig: { icon: "⚡", color: "#f7a41d" },
      v: { icon: "🔷", color: "#5d87bf" },
      d: { icon: "🔴", color: "#ba595e" },
      dart: { icon: "🎯", color: "#00b4ab" },
      sh: { icon: "💻", color: "#89e051" },
      bash: { icon: "💻", color: "#89e051" },
      zsh: { icon: "💻", color: "#89e051" },
      fish: { icon: "🐟", color: "#89e051" },
      ps1: { icon: "💻", color: "#012456" },
      psm1: { icon: "💻", color: "#012456" },
      bat: { icon: "💻", color: "#c1f12e" },
      cmd: { icon: "💻", color: "#c1f12e" },
      md: { icon: "📝", color: "#083fa1" },
      mdx: { icon: "📝", color: "#083fa1" },
      txt: { icon: "📄", color: "#d4d4d8" },
      rst: { icon: "📝", color: "#141414" },
      adoc: { icon: "📝", color: "#e40046" },
      org: { icon: "📝", color: "#77aa99" },
      pdf: { icon: "📕", color: "#ff0000" },
      doc: { icon: "📘", color: "#2b579a" },
      docx: { icon: "📘", color: "#2b579a" },
      xls: { icon: "📗", color: "#217346" },
      xlsx: { icon: "📗", color: "#217346" },
      ppt: { icon: "📙", color: "#d24726" },
      pptx: { icon: "📙", color: "#d24726" },
      odt: { icon: "📄", color: "#0066b3" },
      svg: { icon: "🖼️", color: "#ffb13b" },
      png: { icon: "🖼️", color: "#a074c4" },
      jpg: { icon: "🖼️", color: "#a074c4" },
      jpeg: { icon: "🖼️", color: "#a074c4" },
      gif: { icon: "🖼️", color: "#a074c4" },
      ico: { icon: "🖼️", color: "#a074c4" },
      webp: { icon: "🖼️", color: "#a074c4" },
      bmp: { icon: "🖼️", color: "#a074c4" },
      tiff: { icon: "🖼️", color: "#a074c4" },
      psd: { icon: "🖼️", color: "#31a8ff" },
      ai: { icon: "🖼️", color: "#ff9a00" },
      sketch: { icon: "🖼️", color: "#f7b500" },
      figma: { icon: "🖼️", color: "#a259ff" },
      mp3: { icon: "🎵", color: "#e91e63" },
      wav: { icon: "🎵", color: "#e91e63" },
      ogg: { icon: "🎵", color: "#e91e63" },
      flac: { icon: "🎵", color: "#e91e63" },
      mp4: { icon: "🎬", color: "#f44336" },
      mkv: { icon: "🎬", color: "#f44336" },
      avi: { icon: "🎬", color: "#f44336" },
      mov: { icon: "🎬", color: "#f44336" },
      webm: { icon: "🎬", color: "#f44336" },
      zip: { icon: "📦", color: "#6d8086" },
      tar: { icon: "📦", color: "#6d8086" },
      gz: { icon: "📦", color: "#6d8086" },
      rar: { icon: "📦", color: "#6d8086" },
      "7z": { icon: "📦", color: "#6d8086" },
      bz2: { icon: "📦", color: "#6d8086" },
      xz: { icon: "📦", color: "#6d8086" },
      sql: { icon: "🗃️", color: "#e38c00" },
      db: { icon: "🗃️", color: "#ff5555" },
      sqlite: { icon: "🗃️", color: "#003b57" },
      mongodb: { icon: "🍃", color: "#13aa52" },
      ttf: { icon: "🔤", color: "#ec5252" },
      otf: { icon: "🔤", color: "#ec5252" },
      woff: { icon: "🔤", color: "#ec5252" },
      woff2: { icon: "🔤", color: "#ec5252" },
      eot: { icon: "🔤", color: "#ec5252" },
      pem: { icon: "🔑", color: "#a8b9cc" },
      crt: { icon: "🔑", color: "#a8b9cc" },
      key: { icon: "🔑", color: "#a8b9cc" },
      cer: { icon: "🔑", color: "#a8b9cc" },
      log: { icon: "📜", color: "#6d8086" },
      wasm: { icon: "🔲", color: "#654ff0" },
      dll: { icon: "⚙️", color: "#6d8086" },
      so: { icon: "⚙️", color: "#6d8086" },
      dylib: { icon: "⚙️", color: "#6d8086" },
      o: { icon: "⚙️", color: "#6d8086" },
      a: { icon: "⚙️", color: "#6d8086" },
      exe: { icon: "⚙️", color: "#6d8086" },
      lock: { icon: "🔒", color: "#525252" },
      graphql: { icon: "💠", color: "#e535ab" },
      gql: { icon: "💠", color: "#e535ab" },
      prisma: { icon: "🔺", color: "#1a202c" },
      tf: { icon: "🏗️", color: "#844fba" },
      tfvars: { icon: "🏗️", color: "#844fba" },
      proto: { icon: "📡", color: "#4285f4" },
      mk: { icon: "🔨", color: "#6d8086" },
    },
    fileNames: SETI_FILE_NAMES,
    folderNames: SETI_FOLDER_NAMES,
    folderNamesOpen: {},
  },
};
